on:
  push:
    branches: 
      - main
name: Api Mobile
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{ secrets.ftp_host }}
            username: ${{ secrets.ftp_user }}
            password: ${{ secrets.ftp_password }}
            server-dir: apimobile.vitorads.com.br/